--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LousWiteMC/AdvancedJobs
build-by-default: true
branches:
- master
projects:
  AdvancedJobs:
    icon: icon.png
    path: ""
    libs:
<<<<<<< HEAD
    - src: dktapps/pmforms/
=======
    - src: dktapps-pm-pl/pmforms/pmforms/
>>>>>>> 0ceeaf46033a930ec1f7cd2346af1cd2835b0c01
      version: ^1.0.0
...
